# Generated by Django 4.0.5 on 2022-06-27 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('chapter', models.IntegerField(choices=[(0, 'Chapter 1'), (2, 'Chapter 2')], default=0, verbose_name='chapter')),
                ('number', models.IntegerField(default=0, verbose_name='number')),
                ('slug', models.SlugField(blank=True)),
                ('type', models.IntegerField(choices=[(0, 'Default'), (1, 'Flashback'), (2, 'Subsistence'), (3, 'Stealth')], default=0, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(max_length=2000)),
                ('type', models.IntegerField(choices=[(0, 'Primary'), (1, 'Secondary')], default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='missions.mission')),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
            },
        ),
        migrations.CreateModel(
            name='ObjectiveImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='objectives/')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='missions.objective')),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(max_length=2000)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='missions.mission')),
            ],
            options={
                'verbose_name': 'Fact',
                'verbose_name_plural': 'Facts',
            },
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=2000)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.character')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='missions.mission')),
            ],
            options={
                'verbose_name': 'Dialog',
                'verbose_name_plural': 'Dialogs',
            },
        ),
    ]
