# Generated by Django 4.0.5 on 2022-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
    ]
