# Generated by Django 4.0.5 on 2022-06-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='chapter',
            field=models.IntegerField(default=1),
        ),
    ]
