# Generated by Django 4.0.5 on 2022-06-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Flashback'), (2, 'Autonomy'), (3, 'Stealth')], default=0),
        ),
    ]
