# Generated by Django 4.0.5 on 2022-06-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_character_objective_fact_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='missions.mission'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='missions.mission'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='missions.mission'),
        ),
    ]
