# Generated by Django 4.0.5 on 2022-06-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_alter_dialog_mission_alter_fact_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='type',
            field=models.IntegerField(choices=[(0, 'Primary'), (1, 'Secondary')], default=0),
        ),
    ]
