# Generated by Django 4.0.5 on 2022-06-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_alter_objective_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'verbose_name': 'Objective', 'verbose_name_plural': 'Objectives'},
        ),
    ]
