# Generated by Django 4.0.5 on 2022-06-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_alter_dialog_options_alter_fact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='chapter',
            field=models.IntegerField(choices=[(0, 'Chapter 1'), (2, 'Chapter 2')], default=0, verbose_name='chapter'),
        ),
        migrations.CreateModel(
            name='ObjectiveImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='missions.objective')),
            ],
        ),
    ]
