# Generated by Django 4.0.5 on 2022-06-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0009_alter_mission_chapter_objectiveimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectiveimage',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='objectiveimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
