# Generated by Django 4.0.5 on 2022-06-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0010_alter_objectiveimage_options_objectiveimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='fact',
            name='text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='objective',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
