# Generated by Django 4.0.5 on 2022-06-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0012_alter_objectiveimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.character'),
        ),
        migrations.AlterField(
            model_name='objectiveimage',
            name='image',
            field=models.ImageField(upload_to='objectives/'),
        ),
    ]
